include: package:pedantic/analysis_options.1.11.0.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false

linter:
  rules:
    - camel_case_types
    - close_sinks
    - lines_longer_than_80_chars